import { Letter } from './letters';

// https://qlocktwo.com/eu/timecheck?color=Metamorphite&controls=false&hours=3&language=RO&minutes=25&size=600

const letters_ro: Letter[][] = [
    [
        { name: 'E', sections: ['este'] },
        { name: 'S', sections: ['este'] },
        { name: 'T', sections: ['este'] },
        { name: 'E', sections: ['este'] },
        { name: 'Z', sections: [] },
        { name: 'O', sections: ['ora'] },
        { name: 'R', sections: ['ora'] },
        { name: 'A', sections: ['ora'] },
        { name: 'P', sections: [''] },
        { name: 'M', sections: [] },
        { name: 'O', sections: [] },
    ],
    [
        { name: 'D', sections: ['h-doua', 'h-douasprezece'] },
        { name: 'O', sections: ['h-doua', 'h-douasprezece'] },
        { name: 'U', sections: ['h-doua', 'h-douasprezece'] },
        { name: 'A', sections: ['h-doua', 'h-douasprezece'] },
        { name: 'N', sections: [] },
        { name: 'S', sections: ['spre', 'h-douasprezece'] },
        { name: 'P', sections: ['spre', 'h-douasprezece'] },
        { name: 'R', sections: ['spre', 'h-douasprezece'] },
        { name: 'E', sections: ['spre', 'h-douasprezece'] },
        { name: 'A', sections: [] },
        { name: 'M', sections: [] },
    ],
    [
        { name: 'U', sections: ['h-unsprezece'] },
        { name: 'N', sections: ['h-unsprezece'] },
        { name: 'S', sections: ['h-unsprezece'] },
        { name: 'P', sections: ['h-unsprezece'] },
        { name: 'R', sections: ['h-unsprezece'] },
        { name: 'E', sections: ['h-unsprezece'] },
        { name: 'Z', sections: ['h-zece', 'h-unsprezece', 'h-douasprezece'] },
        { name: 'E', sections: ['h-zece', 'h-unsprezece', 'h-douasprezece'] },
        { name: 'C', sections: ['h-zece', 'h-unsprezece', 'h-douasprezece'] },
        { name: 'E', sections: ['h-zece', 'h-unsprezece', 'h-douasprezece'] },
        { name: 'L', sections: [] },
    ],
    [
        { name: 'N', sections: ['h-noua'] },
        { name: 'O', sections: ['h-noua'] },
        { name: 'U', sections: ['h-noua'] },
        { name: 'A', sections: ['h-noua'] },
        { name: 'O', sections: ['h-opt'] },
        { name: 'P', sections: ['h-opt'] },
        { name: 'T', sections: ['h-opt'] },
        { name: 'S', sections: ['h-sase'] },
        { name: 'A', sections: ['h-sase'] },
        { name: 'S', sections: ['h-sase'] },
        { name: 'E', sections: ['h-sase'] },
    ],
    [
        { name: 'P', sections: ['h-patru'] },
        { name: 'A', sections: ['h-patru'] },
        { name: 'T', sections: ['h-patru'] },
        { name: 'R', sections: ['h-patru'] },
        { name: 'U', sections: ['h-patru', 'h-unu'] },
        { name: 'N', sections: ['h-unu'] },
        { name: 'U', sections: ['h-unu'] },
        { name: 'T', sections: ['h-trei'] },
        { name: 'R', sections: ['h-trei'] },
        { name: 'E', sections: ['h-trei'] },
        { name: 'I', sections: ['h-trei'] },
    ],
    [
        { name: 'S', sections: ['h-sapte'] },
        { name: 'A', sections: ['h-sapte'] },
        { name: 'P', sections: ['h-sapte'] },
        { name: 'T', sections: ['h-sapte'] },
        { name: 'E', sections: ['h-sapte'] },
        { name: 'C', sections: ['h-cinci'] },
        { name: 'I', sections: ['h-cinci'] },
        { name: 'N', sections: ['h-cinci'] },
        { name: 'C', sections: ['h-cinci'] },
        { name: 'I', sections: ['h-cinci'] },
        { name: 'A', sections: [] },
    ],
    [
        { name: 'S', sections: ['si'] },
        { name: 'I', sections: ['si'] },
        { name: 'B', sections: [] },
        { name: 'T', sections: ['m-treizeci'] },
        { name: 'R', sections: ['m-treizeci'] },
        { name: 'E', sections: ['m-treizeci'] },
        { name: 'I', sections: ['m-treizeci'] },
        { name: 'Z', sections: ['m-treizeci'] },
        { name: 'E', sections: ['m-treizeci'] },
        { name: 'C', sections: ['m-treizeci'] },
        { name: 'I', sections: ['m-treizeci'] },
    ],
    [
        { name: 'F', sections: ['fara'] },
        { name: 'A', sections: ['fara'] },
        { name: 'R', sections: ['fara'] },
        { name: 'A', sections: ['fara'] },
        { name: 'O', sections: [] },
        { name: 'Z', sections: ['m-zece'] },
        { name: 'E', sections: ['m-zece'] },
        { name: 'C', sections: ['m-zece'] },
        { name: 'E', sections: ['m-zece'] },
        { name: 'U', sections: ['un'] },
        { name: 'N', sections: ['un'] },
    ],
    [
        { name: 'D', sections: ['m-douazeci'] },
        { name: 'O', sections: ['m-douazeci'] },
        { name: 'U', sections: ['m-douazeci'] },
        { name: 'A', sections: ['m-douazeci'] },
        { name: 'Z', sections: ['m-douazeci'] },
        { name: 'E', sections: ['m-douazeci'] },
        { name: 'C', sections: ['m-douazeci'] },
        { name: 'I', sections: ['m-douazeci'] },
        { name: 'V', sections: [] },
        { name: 'S', sections: ['second-si'] },
        { name: 'I', sections: ['second-si'] },
    ],
    [
        { name: 'C', sections: ['m-cinci'] },
        { name: 'I', sections: ['m-cinci'] },
        { name: 'N', sections: ['m-cinci'] },
        { name: 'C', sections: ['m-cinci'] },
        { name: 'I', sections: ['m-cinci'] },
        { name: 'U', sections: [] },
        { name: 'S', sections: ['sfert'] },
        { name: 'F', sections: ['sfert'] },
        { name: 'E', sections: ['sfert'] },
        { name: 'R', sections: ['sfert'] },
        { name: 'T', sections: ['sfert'] },
    ],
    [
        { name: '+', sections: ['d-1'] },
        { name: '+', sections: ['d-2'] },
        { name: '+', sections: ['d-3'] },
        { name: '+', sections: ['d-4'] },
        { name: ' ', sections: [] },
        { name: ' ', sections: [] },
        { name: ' ', sections: [] },
        { name: 'A', sections: ['am'] },
        { name: 'M', sections: ['am'] },
        { name: 'P', sections: ['pm'] },
        { name: 'M', sections: ['pm'] },
    ],
];

export default letters_ro;
